name: chat_firebase_fcm
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  chat_sdk_core:
    path: ../chat_sdk_core
  chat_platform:
    path: ../chat_platform
  chat_config:
    path: ../chat_config

  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3
  eraser: ^3.0.0
  flutter_app_badger: ^1.5.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

