name: app_chat
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  chat_config:
    path: chat_config
  chat_core:
    path: chat_core
  chat_firebase_fcm:
    path: chat_firebase_fcm
  chat_input_ui:
    path: chat_input_ui
  chat_media_editor:
    path: chat_media_editor
  chat_mention_controller:
    path: chat_mention_controller
  chat_message_page:
    path: chat_message_page
  chat_model:
    path: chat_model
  chat_platform:
    path: chat_platform
  chat_room_page:
    path: chat_room_page
  chat_sdk_core:
    path: chat_sdk_core
  chat_shared_page:
    path: chat_shared_page
  chat_translate:
    path: chat_translate
  chat_translation:
    path: chat_translation
  chat_voice_player:
    path: chat_voice_player
  chat_v2:
    path: chat_v2


  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.0
  badges: ^3.1.2
  http: ^1.3.0
  firebase_messaging: ^15.2.3
  yaml: ^3.1.3
  email_validator: ^3.0.0
  touchable_opacity: ^1.2.0
  package_info_plus: ^8.2.1
  get_it: ^8.0.3
  url_strategy: ^0.3.0
  path_provider: ^2.1.5
  responsive_builder: ^0.7.1
  version: ^3.0.2
  responsive_framework: ^1.5.1
  universal_html: ^2.2.4
  flutter_native_splash: ^2.4.4
  chopper: ^8.1.0
  logging: ^1.3.0
  modal_bottom_sheet: ^3.0.0
  google_fonts: ^6.2.1
  loadmore: ^2.1.0
  intl: ^0.19.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  enum_to_string: ^2.2.0
  adaptive_dialog: ^2.4.0
  pinput: ^5.0.1
  flutter_local_notifications: ^17.2.1
  dashed_circle: ^0.0.2
  story_view: ^0.16.5
  hexcolor: ^3.0.1
  background_downloader: ^8.9.4
  file_sizes: ^1.0.6
  connectycube_flutter_call_kit: ^2.7.0
  permission_handler: ^11.4.0
  window_manager: ^0.4.3
  line_awesome_flutter: ^3.0.1
  number_paginator: ^0.4.3
  data_table_2: ^2.5.18
  sidebarx: ^0.17.1
  lottie: ^3.3.1
  auto_animated: ^3.2.0
  numeral: ^3.0.0
  eva_icons_flutter: ^3.1.0
  toggle_switch: ^2.3.0
  sqflite_common_ffi: ^2.3.4+4
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  chopper_generator: ^8.1.0
  msix: ^2.7.3
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/message/
    - lotties/

  fonts:
    - family: SvnGilroy
      fonts:
        - asset: fonts/svn_gilroy_black_900.otf
          weight: 900
        - asset: fonts/svn_gilroy_bold_700.otf
          weight: 700
        - asset: fonts/svn_gilroy_semibold_600.otf
          weight: 600
        - asset: fonts/svn_gilroy_medium_500.otf
          weight: 500
        - asset: fonts/svn_gilroy_regular_400.otf
          weight: 400
        - asset: fonts/svn_gilroy_light_300.otf
          weight: 300
        - asset: fonts/svn_gilroy_thin_100.otf
          weight: 100

#only for windows app
msix_config:
  display_name: Chat Dev
  publisher_display_name: Swork
  publisher: CN=8A81D011-D5B0-414F-B3F7-A768A6B8C95E
  identity_name: com.an.zumchat
  msix_version: 1.0.0.0
  languages: en
  logo_path: D:\Swork\superup_flutter\apps\super_up_app\assets\logo.png
  store: true
  capabilities: internetClient
  app_installer:
    publish_folder_path: D:\Swork\superup_flutter\apps\super_up_app\installers\msix
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: true
