name: chat_sdk_core
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  chat_platform:
    path: ../chat_platform
  chat_core:
    path: ../chat_core
  chat_model:
    path: ../chat_model
  chat_config:
    path: ../chat_config
  chat_shared_page:
    path: ../chat_shared_page

  event_bus_plus: ^0.6.2
  chopper: ^8.1.0
  http: ^1.3.0
  logging: ^1.3.0
  socket_io_client: ^3.0.2
  shared_preferences: ^2.5.2
  collection: ^1.19.0
  diacritic: ^0.1.6
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  sqflite_common_ffi: ^2.3.4+4
  flutter_parsed_text: ^2.2.1
  uuid: ^4.5.1
  device_info_plus: ^11.3.0
  background_downloader: ^8.9.4
  flutter_cache_manager: ^3.4.1
  platform_local_notifications: ^1.0.2
  flutter_fgbg: ^0.7.1
  connectivity_plus: ^6.1.3
  intl: ^0.20.2
  objectid: ^3.1.0
  enum_to_string: ^2.2.0
  latlong2: ^0.9.1
  google_api_availability: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

