name: chat_platform
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  file_sizes: ^1.0.6
  meta: ^1.15.0
  mime: ^2.0.0
  mime_type: ^1.0.1
  path: ^1.9.0
  universal_html: ^2.2.4
  http_parser: ^4.1.2
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

