// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGqSz2xpO6YEJNK7SYS3dmnU-I8n091v4',
    appId: '1:599964709544:web:4149938ae991ac5542889d',
    messagingSenderId: '599964709544',
    projectId: 'chat-swork-dev',
    authDomain: 'chat-swork-dev.firebaseapp.com',
    storageBucket: 'chat-swork-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOQisDrkgQRxTKa87gytEvFqDLcnEHTZk',
    appId: '1:599964709544:android:645d5d6b5516c00d42889d',
    messagingSenderId: '599964709544',
    projectId: 'chat-swork-dev',
    storageBucket: 'chat-swork-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Pl8fo580yxOWX2wNfkBpax2_ZBflQiY',
    appId: '1:599964709544:ios:6ef2fcae4cb2b3d942889d',
    messagingSenderId: '599964709544',
    projectId: 'chat-swork-dev',
    storageBucket: 'chat-swork-dev.firebasestorage.app',
    iosBundleId: 'com.swork.appChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9Pl8fo580yxOWX2wNfkBpax2_ZBflQiY',
    appId: '1:599964709544:ios:6ef2fcae4cb2b3d942889d',
    messagingSenderId: '599964709544',
    projectId: 'chat-swork-dev',
    storageBucket: 'chat-swork-dev.firebasestorage.app',
    iosBundleId: 'com.swork.appChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGqSz2xpO6YEJNK7SYS3dmnU-I8n091v4',
    appId: '1:599964709544:web:6d0b282b6b23a0bb42889d',
    messagingSenderId: '599964709544',
    projectId: 'chat-swork-dev',
    authDomain: 'chat-swork-dev.firebaseapp.com',
    storageBucket: 'chat-swork-dev.firebasestorage.app',
  );
}
