name: chat_message_page
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  chat_input_ui:
    path: ../chat_input_ui
  chat_sdk_core:
    path: ../chat_sdk_core
  chat_core:
    path: ../chat_core
  chat_voice_player:
    path: ../chat_voice_player
  chat_platform:
    path: ../chat_platform
  chat_translation:
    path: ../chat_translation

  get_it: ^8.0.3
  flutter_dropzone: ^4.2.1
  flutter_blurhash: ^0.8.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  intl: ^0.20.2
  flutter_parsed_text: ^2.2.1
  flutter_link_previewer: ^3.2.2
  background_downloader: ^8.9.4
  open_filex: ^4.6.0
  scroll_to_index: ^3.0.1
  uuid: ^4.5.1
  flutter_cache_manager: ^3.4.1
  share_plus: ^10.1.4
  collection: ^1.19.0
  flutter_advanced_avatar: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

