name: chat_room_page
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  chat_platform:
    path: ../chat_platform
  chat_translation:
    path: ../chat_translation
  chat_core:
    path: ../chat_core
  chat_sdk_core:
    path: ../chat_sdk_core

  collection: ^1.19.0
  intl: ^0.20.2
  flutter_advanced_avatar: ^1.5.2
  loadmore: ^2.1.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

