name: chat_core
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  chat_translation:
    path: ../chat_translation
  chat_platform:
    path: ../chat_platform
  chat_translate:
    path: ../chat_translate
  chat_config:
    path: ../chat_config
  chat_model:
    path: ../chat_model
  chat_shared_page:
    path: ../chat_shared_page

  flutter_smart_dialog: ^4.9.8+6
  phosphor_flutter: ^2.1.0
  timeago: ^3.2.2
  touchable_opacity: ^1.2.0
  chopper: ^8.1.0
  enum_to_string: ^2.2.0
  file_picker: ^9.0.0
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  wechat_camera_picker: ^4.3.7
  shared_preferences: ^2.5.2
  encrypt: ^5.0.3
  device_info_plus: ^11.3.0
  uuid: ^4.5.1
  chewie: ^1.10.0
  flutter_cache_manager: ^3.4.1
  gal: ^2.3.1
  http: ^1.3.0
  universal_html: ^2.2.4
  video_player: ^2.9.3
  cached_network_image: ^3.4.1
  map_launcher: ^3.5.0
  url_launcher: ^6.3.1
  adaptive_dialog: ^2.4.0
  badges: ^3.1.2
  path: ^1.9.0
  path_provider: ^2.1.5
  file_saver: ^0.2.14
  photo_view: ^0.15.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0